name: ReportifyBot Run

on:
  workflow_dispatch:   # permite rodar manualmente pelo GitHub
  schedule:
    - cron: "0 10 * * *"   # roda todo dia às 12h UTC (opcional, pode apagar se não quiser agendar)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar bot (relatório + resumo)
        env:
          MY_API_REPORTFY: ${{ secrets.DISCORD_BOT_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          GITHUB_TOKEN: ${{ secrets.REPORTFY_GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.REPOSITORY }}
          
        run: python ReportfyBot.py
